Update scripts: id, imgurl, cover for download covers.
Madh93/conky-spotify pull request #21
Opened 2023-05-16 15:25 UTC by lipebol

Hello,

I'm new to programming and I've never programmed in shell script before.
I tried hard to try to make it as elegant as possible!

I believe Spotify changed the 'Metadata' structure, and the scripts didn't download the covers.
I changed the way it captures the 'id' and the 'imgurl'. 'imgurl' now comes under 'Metadata'.
In the 'cover' script I added a condition for it to check the 'mpris:spotify' and if it is disabled it writes 'id' = " " and the cover is 'empty.jpg'. I also changed the way it checks if the cover has already been downloaded.

2023-05-16 19:52 UTC, Madh93 requested changes
Nice contribution! It works great.

2023-05-16 19:52 UTC, Madh93 commented on scripts/imgurl.sh
It's better to delete commented-out lines of code :smiley:

2023-05-17 00:23 UTC, lipebol commented on scripts/imgurl.sh
Concluded!
I read pull #18 (Update timestamp) and re-added the line.

2023-05-17 16:26 UTC, Madh93 approved these changes
Thanks! :1st_place_medal:

2023-05-17 16:26 UTC, merged